version: 2.1

jobs:
  build: 
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run: python --version
      - run: python main.py

workflows:
  build_now:
    jobs:
      - build
          