version: 2.1

jobs:
  build: 
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run: python main.py
  
  tests: 
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run: python tests.py
  deploy:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - run: echo "deploying to production server"

workflows:
  build_now:
    jobs:
      - build
      - tests:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
          